name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_employee_pension_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: maven
      - name: Build employee-pension-plan-cli with Maven
        run: mvn -B package --file employee-pension-plan-cli/pom.xml

  build_pamsapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: maven
      - name: Build pamsapp with Maven
        run: mvn -B package --file pamsapp/pom.xml
